First draft of Emojify command
DEATHB4DEFEAT/SimpleModBot pull request #2
Opened 2024-03-22 08:48 UTC by Pspritechologist

No idea if I'm doing this right :)

(Also I couldn't get it to build locally because of some config.json file and I wouldn't know how to test it anyway but it ran fine online :))

2024-03-22 08:52 UTC, Pspritechologist commented on src/utils/emojifyFunc.ts
> +const zWJ = '\u200D'; // This is required to stop emoji from making little emoji babies. Otherwise :regional_indicator_c::regional_indicator_a: would become 🇨🇦
I figure this should paste into Discord fine, but I also have it as a character here >> ‌ <<

2024-04-06 06:14 UTC, Stanford47 commented
I'll make a small update that will help with contributing :) (sorry)

that should give you some time to flesh this out more :3

2024-04-09 01:28 UTC, Stanford47 requested changes
The code looks fine and should work, but, there are 3 things that I would change. (Just me being really nit-picky)

### emojify.ts
- The comma on line 13 should be put on a new line (for formatting reasons)

### emojifyFunc.ts
- The const variable `zWJ` on line 5 isn't necessary, since the zero width joiner is used once in the code (line 148).
- You should use the actual emoji characters when possible, Discord accepts that. example: `"circled_m"` can just be `Ⓜ️` and still work.

That's all :3

2024-04-09 13:28 UTC, Pspritechologist commented
> ### emojifyFunc.ts
> * The const variable `zWJ` on line 5 isn't necessary, since the zero width joiner is used once in the code (line 148).
Using random strings in the middle of functions without documentation is bad practice and I will not be taking part in it, thank you very much.

> * You should use the actual emoji characters when possible, Discord accepts that. example: `"circled_m"` can just be `Ⓜ️` and still work.
> 
> That's all :3
I personally liked having the raw text, but if you insist; It is Emojified~

2024-04-09 15:13 UTC, Stanford47 approved these changes
Thanks :) (you could totally just add a comment about zWJ in the function but it's not that important) approved!

2024-04-09 15:14 UTC, merged